// questions
export const GET_QUESTIONS = 'GET_QUESTIONS'
export const ADD_QUESTION = 'ADD_QUESTION'
export const ANSWER_QUESTION = 'ANSWER_QUESTION'
// users
export const GET_USERS = 'GET_USERS'
export const USER_ADD_QUESTION = 'USER_ADD_QUESTION'
export const USER_ANSWER_QUESTION = 'USER_ANSWER_QUESTION'
// authed user
export const SET_AUTHED_USER = 'SET_AUTHED_USER'
export const REMOVE_AUTHED_USER = 'REMOVE_AUTHED_USER'
